version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pass54321!
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:Pass54321!@mydatabase.cns00c04uj8v.us-east-1.rds.amazonaws.com:5432/mydatabase
      JWT_SECRET: supersecret
      PORT: "8000"
    depends_on:
      - db
    # Optional: keep private (recommended)
    # ports:
    #   - "8001:8000"

  task-service:
    build: ./task-service
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:Pass54321!@mydatabase.cns00c04uj8v.us-east-1.rds.amazonaws.com:5432/mydatabase
      AUTH_SERVICE_URL: http://auth-service:8000
      PORT: "8000"
    depends_on:
      - db
      - auth-service
    # Optional: keep private (recommended)
    # ports:
    #   - "8002:8000"

  api-gateway:
    build: ./api-gateway
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - task-service

volumes:
  db_data:
